import Foundation

enum AppStrings {
    static let appName = "Canope"

    static let library = "Library"
    static let editor = "Editor"
    static let folder = "Folder"
    static let output = "Output"
    static let compare = "Compare"
    static let source = "Source"
    static let preview = "Preview"
    static let references = "References"
    static let panelLayout = "Panel layout"
    static let panelOrder = "Panel order"
    static let annotations = "Annotations"
    static let files = "Files"

    static let allPapers = "All papers"
    static let favorites = "Favorites"
    static let unread = "Unread"
    static let recent = "Recent"
    static let collection = "Collection"
    static let collections = "Collections"
    static let metadata = "Metadata"
    static let rating = "Rating"
    static let notes = "Notes"
    static let info = "Info"

    static let addPhotosAndFiles = "Add photos and files"
    static let includeIDEContext = "Include IDE context"
    static let planMode = "Mode plan"
    static let reasoning = "Reasoning"
    static let customize = "Customize"
    static let noInstructions = "Aucune instruction"
    static let globalActive = "Global actif"
    static let sessionActive = "Session active"
    static let connected = "Connecte"
    static let connecting = "Connecting…"
    static let newClaudeChat = "New Claude chat"
    static let newCodexChat = "New Codex chat"

    static let renameConversation = "Rename conversation"
    static let renameSession = "Rename session"
    static let renameEllipsis = "Rename…"
    static let rename = "Rename"
    static let cancel = "Cancel"
    static let ok = "OK"
    static let name = "Name"

    static let importPDF = "Import PDF"
    static let noPapers = "No papers"
    static let noSelectedPaper = "No paper selected"
    static let selectPaperForInfo = "Select a paper to view its details"
    static let importPDFHint = "Import a PDF with the + button or drop it here"
    static let open = "Open"
    static let delete = "Delete"
    static let removeFlag = "Remove flag"
    static let flag = "Flag"
    static let color = "Color"
    static let shape = "Shape"
    static let addTo = "Add to…"
    static let removeFrom = "Remove from…"
    static let none = "None"

    static let title = "Title"
    static let authors = "Authors"
    static let year = "Year"
    static let journal = "Journal"
    static let doi = "DOI"
    static let favorite = "Favorite"
    static let read = "Read"
    static let flagged = "Flagged"
    static let added = "Added"
    static let modified = "Modified"
    static let openDOI = "Open DOI in browser"

    static let noErrors = "No errors"
    static let compileSucceeded = "Compilation succeeded"
    static let buildError = "Error"
    static let renderError = "Pandoc error"
    static let notYetCompiled = "Not compiled yet"
    static let notYetExported = "Not exported yet"
    static let noArtifact = "No artifacts"
    static let compiledPDF = "Compiled PDF"
    static let exportedPDF = "Exported PDF"
    static let outputReady = "Output ready"
    static let pdfExportReady = "PDF export ready"

    static let openFolder = "Open folder"
    static let recents = "Recents"
    static let noFileOpen = "No file open"
    static let editorPanelEmpty = "The editor pane is empty.\nYou can still browse reference PDFs."
    static let editorStartHint = "Open a .tex, .md, .py, or .R file from the file browser\nor use the + menu in the top-right corner"
    static let paperUnavailable = "No paper available"
    static let pdfNotFound = "PDF not found"
    static let pdfCouldNotLoad = "The PDF could not be loaded"
    static let referencePDFCouldNotLoad = "The reference PDF could not be loaded"

    static let returnToLatestRun = "Return to latest run"
    static let previousRun = "Previous run"
    static let nextRun = "Next run"
    static let refreshSelectedRun = "Refresh selected run"
    static let showArtifactsFolder = "Show artifacts folder"
    static let toggleComparePane = "Show or hide the comparison pane. When it is open, click a plot or PDF in the tree to load it there."
    static let changeSplitOrientation = "Change the internal split orientation"
    static let primaryPreview = "Primary preview"
    static let manualPreview = "Manual preview"
    static let comparison = "Comparison"
    static let manualComparison = "Manual comparison"
    static let manualPreviewStatus = "Manual preview"
    static let noRuns = "No runs yet"
    static let noOutput = "No output"
    static let noArtifactToDisplay = "No artifact to display in this pane."
    static let fit = "Fit"
    static let zoom100 = "100%"
    static let zoomOut = "Zoom out"
    static let zoomIn = "Zoom in"

    static let selected = "Selected"
    static let tools = "Tools"
    static let colors = "Colors"
    static let selection = "Selection"
    static let actions = "Actions"
    static let view = "View"
    static let customColor = "Custom color"
    static let deleteAnnotation = "Delete annotation"
    static let deleteAllAnnotations = "Delete all annotations"
    static let deleteAllAnnotationsQuestion = "Delete all annotations?"
    static let deleteAll = "Delete all"
    static let save = "Save"
    static let exportAnnotationsMarkdown = "Export annotations to Markdown"
    static let terminal = "Terminal"
    static let annotation = "Annotation"
    static let highlight = "Highlight"
    static let underline = "Underline"
    static let strikeThrough = "Strikethrough"
    static let note = "Note"
    static let drawing = "Drawing"
    static let rectangle = "Rectangle"
    static let oval = "Oval"
    static let arrow = "Arrow"
    static let editNoteEllipsis = "Edit note…"

    static let noAnnotations = "No annotations"
    static let highlightOrNoteHint = "Highlight text or place notes"
    static func page(_ label: String) -> String { "Page \(label)" }

    static let couldNotOpenPDF = "Could not open PDF"
    static let couldNotExportAnnotations = "Could not export annotations"
    static let couldNotCreateFile = "Could not create file"
    static let couldNotRead = "[Could not read]"
    static let couldNotExport = "Could not export annotations"
    static let noChanges = "No changes"
    static let unsavedChangesHint = "Unsaved file changes will appear here."
    static let allChanges = "All changes"
    static let rejectAll = "Reject all"
    static let acceptAll = "Accept all"
    static let attached = "Attached"
    static let needsRelink = "Needs relink"
    static let newLatexFile = "New LaTeX file"
    static let newMarkdownFile = "New Markdown file"
    static let newPythonScript = "New Python script"
    static let newRScript = "New R script"
    static let createEditableFile = "Create a new editable file"
    static let createTexInCurrentFolder = "Create a new .tex file in the current folder"
    static let createMarkdownInCurrentFolder = "Create a new .md file in the current folder"
    static let createPythonInCurrentFolder = "Create a new .py script in the current folder"
    static let createRInCurrentFolder = "Create a new .R script in the current folder"
    static let writeOutputsHint = "Write your outputs to artifact_dir, for example artifact_dir / \"plot.png\""
    static let writeROutputsHint = "Write your outputs to artifact_dir, for example file.path(artifact_dir, \"plot.png\")"

    static let settingsTerminal = "Terminal settings"
    static let useOptionAsMeta = "Use Option as Meta for this terminal tab"
    static let newTerminal = "New terminal"
    static let closeSplit = "Close split"

    static let currentMode = "Current mode · Shift+Tab to cycle"
    static let networkActive = "Network active"
    static let customInstructions = "Custom instructions"
    static let modelLabel = "Model"
    static let reasoningLabel = "Reasoning"
    static let modeLabel = "Mode"
    static let presetHelp = "Active Codex chat preset"
    static let codexModelHelp = "Codex model"
    static let codexExecutionContextHelp = "Codex execution context"
    static let codexReasoningHelp = "Reasoning level"
    static let addOrConfigureMessage = "Add or configure the message"
    static let attachFile = "Attach file"
    static let copy = "Copy"
    static let fork = "Fork"
    static let edit = "Edit"
    static let noActionsApplied = "No actions applied"
    static let activeMarkdown = "Active Markdown"
    static let companionFile = "Companion file"
    static let chooseMarkdownFile = "Choose a Markdown file…"
    static let exportedAnnotations = "Annotations exported"
    static let rendered = "Rendering…"
    static let compiling = "Compiling…"
    static let running = "Running…"
    static let saved = "Saved"
    static let completed = "Completed"
    static let previewReady = "PDF ready"
    static func errorCount(_ count: Int) -> String { "\(count) error\(count == 1 ? "" : "s")" }
    static let codexPromptOnly = "These instructions apply only to the Codex chat."
    static let instructions = "Instructions"
    static let globalInstructions = "Global instructions"
    static let sessionInstructions = "Instructions for this session"
    static let globalInstructionsSubtitle = "Always active for all Codex chats."
    static let sessionInstructionsSubtitle = "Active only for the current conversation."
    static let fastModeUnavailable = "Fast mode is not wired to Canope's Codex backend yet."
    static let commandDeclined = "Commande refusee"
    static let commandFailed = "Commande echouee"
    static let commandCompleted = "Commande terminee"
    static let changeDeclined = "refusee"
    static let changeNotApplied = "non appliquee"
    static let changeApplied = "appliquee"
    static let toolCallFailed = "Appel d’outil echoue"
    static let toolCallCompleted = "Appel d’outil termine"
    static let noPaperAvailable = "No paper available"
    static let openReferencePaper = "Open a reference paper"
    static let markdownPreview = "Markdown Preview"

    static let mutatingActionBlockedPrefix = "Mode plan: l’action mutante"
    static let mutatingActionBlockedSuffix = "a ete bloquee."
    static let permissionRequestBlocked = "Mode plan: la demande de permission additionnelle a ete bloquee."
    static let codexError = "Codex error"
    static let startConversationBeforeReview = "Codex: start a conversation before /review."
    static let userInputCancelled = "Codex: user input cancelled."
    static let errorPrefix = "Error:"
    static let unknownError = "Unknown error"

    static func runStatus(index: Int, total: Int, time: String, artifactCount: Int) -> String {
        "Run \(index)/\(total) · \(time) · \(artifactCount) artifact\(artifactCount == 1 ? "" : "s")"
    }
}
